# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

# This is a basic workflow to help you get started with Actions

name: Run Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "develop/Login" ]
  pull_request:
    branches: [ "develop/Login" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          xcode-version: latest-stable
      - name: Use xcconfig file
        env:
          XC_CONFIG_FILE: ${{ secrets.XC_CONFIG_FILE }}
        run:
          echo "$XC_CONFIG_FILE" > Config.xcconfig
          
      # Runs a single command using the runners shell
      - name: Start Xcode Project!!
        env: 
          XC_CONFIG_FILE: ${{ secrets.XC_CONFIG_FILE }}
        run: | 
          echo "$XC_CONFIG_FILE" > Config.xcconfig, 
          xcodebuild clean test -project Ddungja/Ddungja.xcodeproj -scheme Ddungja CODE_SIGNING_ALLOWED=NO -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=latest'
